'''
VIDEO_POSE - This script filters and scales pre-existing tracking data.

It loads raw tracking data generated by video_detect.py, filters it for
pre-selected track IDs, applies scaling factors, and saves the final data
to a .mat file.

Configuration is loaded from 'config.json'.

Inputs:
    - A .mat file with raw tracking data (path specified in config.json).
    - A list of track IDs to filter for (in config.json).

Outputs:
    - A .mat file containing the filtered and scaled bounding box data.
      (path specified in config.json).

Author: Tiago Simões
Project: VIENA
Instituto Superior Técnico
October 2024; Last revision: 21-September-2025
''' 
#------------- BEGIN MAIN FUNCTION ---------------

import numpy as np
from scipy.io import loadmat, savemat
import json
import os

def get_unique_filepath(filepath):
    """
    Checks if a file exists and returns a unique filepath with a numeric suffix if it does.
    """
    if not os.path.exists(filepath):
        return filepath

    directory, filename = os.path.split(filepath)
    name, ext = os.path.splitext(filename)
    counter = 1
    while True:
        new_name = f"{name}_{counter}{ext}"
        new_filepath = os.path.join(directory, new_name)
        if not os.path.exists(new_filepath):
            return new_filepath
        counter += 1

# Load configuration from config.json
with open('config.json', 'r') as f:
    config = json.load(f)['video_filter']

# Get parameters from config
save_status = config['save']
filter_track_ids = config.get('filter_track_ids', [])
if not filter_track_ids:
    print("Error: 'filter_track_ids' is empty. Please specify track IDs in config.json for video_pose.")
    exit()

x_scale = config.get('x_scale', 1.0)
y_scale = config.get('y_scale', 1.0)
w_scale = config.get('w_scale', 1.0)
h_scale = config.get('h_scale', 1.0)

input_raw_data_path = config['input_raw_data_path']
output_mat_path = config['output_mat_path']

# Check if input file exists
if not os.path.exists(input_raw_data_path):
    print(f"Error: Input data file not found at '{input_raw_data_path}'")
    print("Please run video_detect.py first to generate the raw data file.")
    exit()

# Load the raw tracking data
raw_data = loadmat(input_raw_data_path)['bboxDataAll']

# Filter the data
filtered_bbox_list = []
# The data loaded from the .mat file is a 2D array (shape 1xN), so we iterate over the first row.
for record in raw_data[0]:
    # Each 'record' is a structured element (np.void).
    # The values within are arrays, so we use .item() to extract the scalar.
    track_id = record['track_id'].item()
    if track_id in filter_track_ids:
        # Apply scaling
        frame = record['frame'].item()
        x_resized = record['x'].item() * x_scale
        y_resized = record['y'].item() * y_scale
        w_resized = record['w'].item() * w_scale
        h_resized = record['h'].item() * h_scale
        
        filtered_bbox_list.append((frame, x_resized, y_resized, w_resized, h_resized))

# Save the filtered and scaled data
if save_status:
    if not filtered_bbox_list:
        print("Warning: No data found for the specified track IDs. Output file will not be created.")
    else:
        output_dir = os.path.dirname(output_mat_path)
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        dtype = [('frame', 'int32'), ('x', 'float64'), ('y', 'float64'), ('w', 'float64'), ('h', 'float64')]
        bboxArray = np.array(filtered_bbox_list, dtype=dtype)

        unique_output_mat_path = get_unique_filepath(output_mat_path)

        savemat(unique_output_mat_path, {'bboxArray': bboxArray})
        print(f"Saved filtered tracking data to {unique_output_mat_path}")

#------------- END OF MAIN FUNCTION --------------