function ret= addpathxinfo

% Usage assuming "matlab.my\util\addpathx.m" is in the path:
% >> addpathx('; ...c:\my\folder\containing\this\folder'; ...)
% (please make sure addpathx.m is upto date)

ret= {
    '', 'ekf'; ...
	'', 'multitasking'; ...
    '', 'ptz'; ...
    '', 'virtual_world'; ...
    '', 'virtual_world/vrml_objects'; ...
    '', 'wmr'; ...
    };

return
