%-------------------------------------------------
%
% DEMO_VIDEO_SUB - Demonstrates the usage of the video_sub function.
% This script provides two demos:
% 1. Simple background subtraction on a video.
% 2. Background subtraction with an additional bounding box mask, using
%    data from a .mat file (e.g., generated by YOLO tracking).
%
% Inputs:
%   None
%
% Outputs:
%   output_video_1 : file : Video file with simple background subtraction saved to output_path_1.
%   output_video_2 : file : Video file with background subtraction and bounding box mask saved to output_path_2.
%
% Other m-files required: video_sub.m
% Subfunctions: None
% MAT-files required: tracking_bbox.mat (for Demo 2)
%
% Author: Tiago Simões
% Project: VIENA
% Instituto Superior Técnico
% March 2024; Last revision: 9-September-2025
%
%------------- BEGIN MAIN FUNCTION ---------------

function demo_video_sub()

    % --- Demo 1: Simple background subtraction ---
    disp('Running demo 1 - Video Subtraction');

    % Define file paths
    video_path = 'Viena_30s.mp4';
    background_path = 'viena_background.jpg';
    output_vidsub_path_1 = 'video_vidsub_out_1.mp4';
    output_mask_path_1 = 'video_mask_out_1.mp4';

    % Set threshold
    threshold = 0.1;

    % Run the video subtraction function
    video_sub(video_path, background_path, threshold, output_vidsub_path_1, output_mask_path_1);
    fprintf('\nDemo for video_sub completed.\n');

    % --- Demo 2: Background subtraction with bounding box mask ---
    disp('Running demo 2 - Video Substraction with Bounding Box Mask');

    % Define file paths
    bbox_data_path = 'tracking_bbox.mat';
    output_vidsub_path_2 = 'video_vidsub_out_2.mp4';
    output_mask_path_2 = 'video_mask_out_2.mp4';

    % Set track ID
    track_id = 1;

    % Run the video subtraction function with bounding box mask
    video_sub(video_path, background_path, threshold, output_vidsub_path_2, output_mask_path_2, track_id, bbox_data_path);
    fprintf('\nDemo for video_sub with bounding box mask completed.\n');
end

%------------- END OF MAIN FUNCTION --------------